# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME=""
fpath+=($HOME/.zsh/pure)
autoload -U promptinit; promptinit
prompt pure

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

config() {
  messageUsage="""
  usage: 
    config <command> <config>
  help:
    config --help
    config <command> --help
  commands:
    open    opens the config specified"""

  messageCommands="""
  usage:
    config open <config>
  configs:
    zsh
    bash
    ssh
    git
    hosts"""

  messageInvalidCommand="\nInvalid command. See --help."
  messageInvalidConfig="\nInvalid config. See --help."

  if [[ "$1" == "" ]] || [[ "$1" == "--help" ]] ; then
    echo $messageUsage
  elif [[ "$1" == "open" ]] ; then
    if [[ "$2" == "--help" ]] ; then
      echo $messageCommands
    elif [[ "$2" == "zsh" ]] ; then
      code ~/.zshrc
    elif [[ $2 == "bash" ]] ; then
      code ~/.bashrc
    elif [[ $2 == "ssh" ]] ; then
      code ~/.ssh/config
    elif [[ $2 == "git" ]] ; then
      code ~/.gitconfig
    elif [[ $2 == "hosts" ]] ; then
      code /etc/hosts
    else
      echo $messageInvalidConfig
    fi
  else
    echo $messageInvalidCommand
  fi
}
